### PR TITLE
When performing experiments on an adhoc network, it is useful to

### PR DESCRIPTION
**Pull request by daviddoria**
be able to tell which device is which at a glance. This patch
displays the IP of the device in the top bar of the MANET Manager.

### CODE REVIEW

**Comment by jrobble** [comment]
Small thing: Please declare tvIPAddress and tvSSID as private. 
Medium thing: Please show the IP and SSID in the same font as the temp. You might be able to show both at once.
Big thing: When the screen orientation changes, the IP label goes back to showing "none". Please fix.
Thanks for sharing. With those changes I'll merge this update into master.

**Comment by daviddoria** [comment]
Yep, that certainly is a big thing. I'll fix it (and the medium and little things) Monday and get back to you. You'll notice that I actually commented out all of the SSID display. We found that we were only using the default SSID for all devices, so the IP was the only thing we wanted easy access to to make the experiments flow. It's easy to display the SSID - please let me know if you'd rather display only the IP or both the IP and SSID.

**Comment by jrobble** [comment]
If you can fit both the IP and SSID using the smaller font size then that would be great. If not, then just the IP is fine.

**Comment by daviddoria** [comment]
I made a new pull request from a branch called DisplayInfo (I realize now that pull requests are associated with branches, not commits - this is obviously much cleaner than the mess of a pull request that was from daviddoria:master haha) with your suggestions implemented.

**Comment by jrobble** [comment]
Please see: https://github.com/ProjectSPAN/android-manet-manager/pull/16

**Pull request closed without merging**
